# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

name: Bicep Deployment

variables:
  location: 'UKSouth'
  templateFile: '$(Build.SourcesDirectory)/bicep/main.bicep'
  parametersFile: '$(Build.SourcesDirectory)/bicep/parameters/parameters.json'

pool:
  vmImage: ubuntu-latest

steps:
  - task: AzureResourceManagerTemplateDeployment@3
    inputs:
      deploymentScope: 'Subscription'
      azureResourceManagerConnection: 'FSP-VS-Sub'
      deploymentMode: Incremental
      location: $(location)
      templateLocation: 'Linked artifact'
      csmFile: $(templateFile)
      csmParametersFile: $(parametersFile)
      overrideParameters: '-namePrefix $(namePrefix) -domain $(domain) -adminUserName $(adminusername) -adminPassword $(password)'
